# Generated by Django 4.2.16 on 2026-03-18 22:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="EvidenceLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField()),
                (
                    "color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Color should match HEX format, e.g. #22AA77",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("contraindications", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Remedy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("recipe", models.TextField()),
                ("risks", models.TextField(blank=True)),
                ("source", models.URLField(blank=True, max_length=1024)),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remedies",
                        to="core.disease",
                    ),
                ),
                (
                    "evidence_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remedies",
                        to="core.evidencelevel",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Symptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="UserRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=128)),
                ("is_like", models.BooleanField()),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "remedy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="core.remedy",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RemedyIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.CharField(max_length=255)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_remedies",
                        to="core.ingredient",
                    ),
                ),
                (
                    "remedy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remedy_ingredients",
                        to="core.remedy",
                    ),
                ),
            ],
            options={
                "ordering": ("remedy__name", "ingredient__name"),
            },
        ),
        migrations.AddField(
            model_name="remedy",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="remedies",
                through="core.RemedyIngredient",
                to="core.ingredient",
            ),
        ),
        migrations.CreateModel(
            name="DiseaseSymptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField(default=1.0)),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disease_symptoms",
                        to="core.disease",
                    ),
                ),
                (
                    "symptom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symptom_diseases",
                        to="core.symptom",
                    ),
                ),
            ],
            options={
                "ordering": ("disease__name", "symptom__name"),
            },
        ),
        migrations.AddField(
            model_name="disease",
            name="symptoms",
            field=models.ManyToManyField(
                related_name="diseases",
                through="core.DiseaseSymptom",
                to="core.symptom",
            ),
        ),
        migrations.AddConstraint(
            model_name="userrating",
            constraint=models.UniqueConstraint(
                fields=("user_id", "remedy"), name="unique_user_remedy_rating"
            ),
        ),
        migrations.AddConstraint(
            model_name="remedyingredient",
            constraint=models.UniqueConstraint(
                fields=("remedy", "ingredient"), name="unique_remedy_ingredient"
            ),
        ),
        migrations.AddConstraint(
            model_name="diseasesymptom",
            constraint=models.UniqueConstraint(
                fields=("disease", "symptom"), name="unique_disease_symptom"
            ),
        ),
    ]
