# Generated by Django 4.2.16 on 2026-03-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evidencelevel",
            options={"ordering": ("-rank", "code")},
        ),
        migrations.AddField(
            model_name="evidencelevel",
            name="rank",
            field=models.IntegerField(default=1),
        ),
    ]
