# Generated by Django 4.2.16 on 2026-03-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_evidencelevel_options_evidencelevel_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="remedy",
            name="dislikes_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="remedy",
            name="likes_count",
            field=models.IntegerField(default=0),
        ),
    ]
