# Generated by Django 4.2.16 on 2026-03-19 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_deviceregistration"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=128)),
                ("event_type", models.CharField(max_length=128)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="PrivacyPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=32)),
                ("content", models.TextField()),
                ("effective_from", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-effective_from", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("arab", "Arab"),
                            ("persian", "Persian"),
                            ("caucasian", "Caucasian"),
                            ("turkic", "Turkic"),
                            ("chinese", "Chinese"),
                            ("indian", "Indian"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("book", "Book"),
                            ("website", "Website"),
                            ("treatise", "Treatise"),
                            ("article", "Article"),
                            ("ethnography", "Ethnography"),
                            ("archive", "Archive"),
                        ],
                        default="book",
                        max_length=32,
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=1024)),
                ("reference", models.CharField(blank=True, max_length=1024)),
            ],
            options={
                "ordering": ("title", "author"),
            },
        ),
        migrations.CreateModel(
            name="TermsOfService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=32)),
                ("content", models.TextField()),
                ("effective_from", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-effective_from", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="UserConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=128)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("terms_of_service", "Terms of Service"),
                            ("privacy_policy", "Privacy Policy"),
                        ],
                        max_length=32,
                    ),
                ),
                ("version", models.CharField(max_length=32)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.AddField(
            model_name="ingredient",
            name="alternative_names",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="remedy",
            name="cultural_context",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="remedy",
            name="region",
            field=models.CharField(
                choices=[
                    ("arab", "Arab"),
                    ("persian", "Persian"),
                    ("caucasian", "Caucasian"),
                    ("turkic", "Turkic"),
                    ("chinese", "Chinese"),
                    ("indian", "Indian"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="userconsent",
            constraint=models.UniqueConstraint(
                fields=("user_id", "document_type", "version"),
                name="unique_user_document_consent",
            ),
        ),
        migrations.AddConstraint(
            model_name="termsofservice",
            constraint=models.UniqueConstraint(
                fields=("version",), name="unique_terms_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.UniqueConstraint(
                fields=("title", "author", "year"), name="unique_source_record"
            ),
        ),
        migrations.AddConstraint(
            model_name="privacypolicy",
            constraint=models.UniqueConstraint(
                fields=("version",), name="unique_privacy_version"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["event_type", "-timestamp"], name="analytics_event_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["user_id", "-timestamp"], name="analytics_user_idx"
            ),
        ),
        migrations.AddField(
            model_name="remedy",
            name="source_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remedies",
                to="core.source",
            ),
        ),
    ]
