# Generated by Django 4.2.16 on 2026-03-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_analyticsevent_privacypolicy_source_termsofservice_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="favorite",
            index=models.Index(
                fields=["user_id", "-created_at"], name="favorite_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="remedy",
            index=models.Index(fields=["region"], name="remedy_region_idx"),
        ),
        migrations.AddIndex(
            model_name="remedy",
            index=models.Index(
                fields=["disease", "region"], name="remedy_disease_region_idx"
            ),
        ),
    ]
